export const GET_SURVAY = '[Survay] GET_SURVAY'
export type GET_SURVAY = typeof GET_SURVAY

export const GET_SURVAY_SUCCESS = '[Survay] GET_SURVAY_SUCCESS'
export type GET_SURVAY_SUCCESS = typeof GET_SURVAY_SUCCESS

export const CREATE_SURVAY_ANSWER = '[Survay] CREATE_SURVAY_ANSWER'
export type CREATE_SURVAY_ANSWER = typeof CREATE_SURVAY_ANSWER

export const CREATE_SURVAY_ANSWER_SUCCESS = '[Survay] CREATE_SURVAY_ANSWER_SUCCESS'
export type CREATE_SURVAY_ANSWER_SUCCESS = typeof CREATE_SURVAY_ANSWER_SUCCESS

export const GET_SURVAY_ANSWERS = '[Survay] GET_SURVAY_ANSWERS'
export type GET_SURVAY_ANSWERS = typeof GET_SURVAY_ANSWERS

export const GET_SURVAY_ANSWERS_SUCCESS = '[Survay] GET_SURVAY_ANSWERS_SUCCESS'
export type GET_SURVAY_ANSWERS_SUCCESS = typeof GET_SURVAY_ANSWERS_SUCCESS

export const SURVAY_HAS_ERRORED = '[Survay] SURVAY_HAS_ERRORED'
export type SURVAY_HAS_ERRORED = typeof SURVAY_HAS_ERRORED